/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "switch.h"
#include "adc.h"
#include "i2c_lcd.h"
#include "uart.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	SwitchInit(SWITCH);
	LcdInit();
	ADC_Init();
	LcdPuts(LCD_LINE1, "DESD @ Sunbeam\n");
	LcdPuts(LCD_LINE2, "STM32 RTC Demo!\n");
	UartInit(BAUD_9600);
	UartPuts("DESD ADC Demo...\r\n");
	UartPuts("\r\n");
	LcdWrite(LCD_CMD, LCD_CLEAR);

	char str1[24], str2[20];
	uint16_t val;
	uint16_t val1;

	int pState = 0;
	int cState = 0;
    int cycle = 0;
    DelayMs(1000);

    while(1)
    {
    	val = ADC_GetValue();

    	if(val > 4095)
    		val = 1;

    	if(val < 4094)
    	{
    		cycle = 0;
    		cState = 0;
    	}

    	else if(val > 4094)
    	{
    		cycle = 1;
    		cState = 1;
    	}

    	if(cycle == 1)
    	{
    		DelayMs(200);
    		val = ADC_GetValue();
    		val1 = val;
    		cycle = 0;
    	}

    	if(cycle == 0)
    	{
    		if(cState != pState)
    		{
    			sprintf(str1, "LDR = %d", val1);
    			sprintf(str2, "Switch = %d", cycle);
    			UartPuts(str1);
    			UartPuts("		");
    			UartPuts(str2);
    			UartPuts("		");
    			UartPuts("\r\n");
    			LcdPuts(LCD_LINE1, str1);
        	    LcdPuts(LCD_LINE2, str2);
    		}
    	    pState = cState;
    	}
    }
	return 0;
}


